### ISSUE TITLE
As a big fan of your program, I have used it for over 200 hours and thank you very much for your creation.

### ISSUE THREAD

**Issue by haohaoya12** [Kramar1337/Deadlock-AHK-External#10]
Как преданный фанат вашей программы, я использовал 200 часов, чтобы поблагодарить вас за вашу работу.

Среди них я рассматриваю некоторые проблемы, с которыми сталкиваюсь, краткое изложение, которое, надеюсь, сделает программу более совершенной:
1. Поскольку у каждого персонажа в игре свои скелетометрические параметры, различные герои также должны внести коррективы в параметры, зафиксированные на шее, и многие игровые персонажи по-прежнему запирают головы.(вы, конечно, сделали возможное приспособление, идеально)
2. В случае наличия нескольких врагов в пределах диапазона aimbox, aimbox автоматически блокирует более близкого врага, чем предыдущего, что приводит к тому, что враг убегает, когда его жизнь находится в опасности.
3. По причинам расстояния, во многих случаях aimbox блокирует невидимую душу или врага на большом расстоянии, что приводит к тому, что она очень яркая в глазах зрителя или зрителя.
4. за долгое время использования, я так и не смог использовать функцию «радар перспективы», потому что изображение покрывало первоначальную голову врага и открывало то, что было показано на карте словами «вражеское имя».Так что я не могу четко разглядеть героя на радаре.
Небольшая проблемка, ха-ха.После случайного имени файла, мне нужно будет редактировать каждый раз, чтобы узнать конкретные функции файла.

**Comment by haohaoya12** [comment]
Плохой перевод, надеюсь, ты понимаешь

**Comment by haohaoya12** [comment]
As a big fan of your program, I have used it for over 200 hours and thank you very much for your creation.



Among them, I put some problems I encountered, a simple description, hoping to make the program more perfect:

1. Due to the different bone parameters of each character in the game, different heroes also need to adjust the parameters of locking the neck, and the result of not adjusting is that many game characters will still lock the head. (Of course, you've made the adjustment possible, and it's perfect)

2. When there are multiple enemies in the aimbox area, aimbox will automatically lock on to the closer enemy instead of continuing to pursue the previous enemy, which leads to many times, the enemy will flee when life is in danger.

3. Due to the distance, many times aimbox will lock on an invisible soul or enemy at a distance, which makes it very obvious in the replay or the audience's eyes.

4. In fact, I have not used the "perspective radar" function for such a long time, because the image has covered the original enemy head, and the "enemy name" is very messy on the map. So I can't see specific heroes on the radar.

5. A trivial problem, haha. After the random file name, I need to edit it every time to open it to know the specific function of the file.

**Comment by Kramar1337** [comment]
Hi. Thanks for the feedback.
1. The player model uses 100 bones, the bone indices overlap each other, I tried when I selected the head indices, but I did the neck indices carelessly.
2. Yes, this problem is very annoying. I know. I will fix it later when I have time.
3. I did not understand what you mean. It seems that when you press the aimbot key, you aim at objects that are out of sight. This problem cannot be solved, you can control it by pressing and releasing the aimbot key. Perhaps you have seen the "visibility check" function in other projects, even if I get my hands on the source code, it is difficult to implement in the AHK programming language.
4. This is strange. For me, the radar works perfectly. It is superimposed on the in-game radar and I see EVERYTHING! Allies are green without a name, enemies are red with a name. I use a 2560-1440 monitor, I checked on 1920-1080 it works equally well, also there is a hotkey "Alt" to hide the radar. I have full control over the map and see everything. There is a setting in the config file:
Image transparency
imageAlpha=0.3
You can experiment with the settings.
5. Random name generator makes a random name. It looks confusing, but you can remove unnecessary functions and then changing the name will not matter.

At the time of release, my program was the best (because it was the only one. WH, Aim, Radar). But now there are many other programs made better. For example:
https://github.com/Loara228/deadlock-esp
Or
https://www.unknowncheats.me/forum/deadlock/
I need to improve a lot.
I want:

Automatic parry
Display creep HP
Display boxes
Add HWID Spoofer
My program uses Memory Write, I need to get rid of it, leave only reading.

As soon as I have free time, I will gradually add and remove something.

**Comment by haohaoya12** [comment]
Actually, there is a small issue. After using it for such a long time, the program "AIMBOX SOUL" that you updated later, when the "no backseat" function is enabled, the mouse will move downwards, which may require a slight lift of the mouse to lock the soul. I don't know if it is an issue with my "sleepgpu" parameter being set to 20.
